[project]
name = "html2htpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.1",
    "htpy>=25.10.0",
    "pygments>=2.19.2",
    "ruff>=0.14.4",
]
